package de.hahn.blog.libtest.master.model.adfbc.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 18 18:31:30 CET 2013
// ---------------------------------------------------------------------
public interface BlogLibTestMasterAppModule extends ApplicationModule {
    String helloMasterModule(String param);
}
