package de.hahn.blog.libtest.empmodel.adfbc.service.client;

import de.hahn.blog.libtest.empmodel.adfbc.service.common.EmpAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 18 18:24:37 CET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpAppModuleClient extends ApplicationModuleImpl implements EmpAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpAppModuleClient() {
    }

    public String helloEmpModule(String param) {
        Object _ret = this.riInvokeExportedMethod(this,"helloEmpModule",new String [] {"java.lang.String"},new Object[] {param});
        return (String)_ret;
    }
}
