package de.hahn.blog.libtest.regionmodel.adfbc.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 21 19:49:19 CET 2013
// ---------------------------------------------------------------------
public interface RegionModelAppModule extends ApplicationModule {
    String helloRegionModule(String param);
}
