package de.hahn.blog.libtest.depmodel.adfbc.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 18 18:26:06 CET 2013
// ---------------------------------------------------------------------
public interface DepAppModule extends ApplicationModule {
    String helloDepModule(String param);
}
