package de.hahn.blog.libtest.empmodel.adfbc.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 18 18:24:36 CET 2013
// ---------------------------------------------------------------------
public interface EmpAppModule extends ApplicationModule {
    String helloEmpModule(String param);
}
