package de.hahn.blog.libtest.master.model.adfbc.service.client;

import de.hahn.blog.libtest.depmodel.adfbc.service.common.DepAppModule;
import de.hahn.blog.libtest.empmodel.adfbc.service.common.EmpAppModule;
import de.hahn.blog.libtest.master.model.adfbc.service.common.BlogLibTestMasterAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 18 18:31:30 CET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BlogLibTestMasterAppModuleClient extends ApplicationModuleImpl implements BlogLibTestMasterAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public BlogLibTestMasterAppModuleClient() {
    }

    public String helloMasterModule(String param) {
        Object _ret = this.riInvokeExportedMethod(this,"helloMasterModule",new String [] {"java.lang.String"},new Object[] {param});
        return (String)_ret;
    }

    public DepAppModule getDepAppModule() {
        return (DepAppModule)findApplicationModule("DepAppModule");
    }

    public EmpAppModule getEmpAppModule() {
        return (EmpAppModule)findApplicationModule("EmpAppModule");
    }
}
