package de.hahn.blog.libtest.regionmodel.adfbc.service.client;

import de.hahn.blog.libtest.regionmodel.adfbc.service.common.RegionModelAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 21 19:49:22 CET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionModelAppModuleClient extends ApplicationModuleImpl implements RegionModelAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public RegionModelAppModuleClient() {
    }

    public String helloRegionModule(String param) {
        Object _ret = this.riInvokeExportedMethod(this,"helloRegionModule",new String [] {"java.lang.String"},new Object[] {param});
        return (String)_ret;
    }
}
