package de.hahn.blog.libtest.depmodel.adfbc.service;

import de.hahn.blog.libtest.depmodel.adfbc.service.common.DepAppModule;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 18 18:15:30 CET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepAppModuleImpl extends ApplicationModuleImpl implements DepAppModule {
    private static ADFLogger logger = ADFLogger.createADFLogger(DepAppModuleImpl.class);
    /**
     * This is the default constructor (do not remove).
     */
    public DepAppModuleImpl() {
    }

    /**
     * Container's getter for CountriesView1.
     * @return CountriesView1
     */
    public ViewObjectImpl getCountriesView1() {
        return (ViewObjectImpl)findViewObject("CountriesView1");
    }

    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public ViewObjectImpl getDepartmentsView1() {
        return (ViewObjectImpl)findViewObject("DepartmentsView1");
    }

    /**
     * Container's getter for LocationsView1.
     * @return LocationsView1
     */
    public ViewObjectImpl getLocationsView1() {
        return (ViewObjectImpl)findViewObject("LocationsView1");
    }

    /**
     * Container's getter for RegionsView1.
     * @return RegionsView1
     */
    public ViewObjectImpl getRegionsView1() {
        return (ViewObjectImpl)findViewObject("RegionsView1");
    }

    /**
     * Container's getter for DepartmentsView2.
     * @return DepartmentsView2
     */
    public ViewObjectImpl getDepartmentsView2() {
        return (ViewObjectImpl)findViewObject("DepartmentsView2");
    }

    /**
     * Container's getter for LocationsView2.
     * @return LocationsView2
     */
    public ViewObjectImpl getLocationsView2() {
        return (ViewObjectImpl)findViewObject("LocationsView2");
    }

    /**
     * Container's getter for CountriesView2.
     * @return CountriesView2
     */
    public ViewObjectImpl getCountriesView2() {
        return (ViewObjectImpl)findViewObject("CountriesView2");
    }

    /**
     * Container's getter for DeptLocFkLink1.
     * @return DeptLocFkLink1
     */
    public ViewLinkImpl getDeptLocFkLink1() {
        return (ViewLinkImpl)findViewLink("DeptLocFkLink1");
    }

    /**
     * Container's getter for LocCIdFkLink1.
     * @return LocCIdFkLink1
     */
    public ViewLinkImpl getLocCIdFkLink1() {
        return (ViewLinkImpl)findViewLink("LocCIdFkLink1");
    }

    /**
     * Container's getter for CountrRegFkLink1.
     * @return CountrRegFkLink1
     */
    public ViewLinkImpl getCountrRegFkLink1() {
        return (ViewLinkImpl)findViewLink("CountrRegFkLink1");
    }
    public String helloDepModule(String param) {
        logger.info("Param = " + param);
        if (param != null)
            return "Hello " + param;
        return "Can't say hello to nobody";
    }
}
