package de.hahn.blog.libtest.regionmodel.adfbc.service;

import de.hahn.blog.libtest.regionmodel.adfbc.service.common.RegionModelAppModule;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 20 11:46:24 CET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionModelAppModuleImpl extends ApplicationModuleImpl implements RegionModelAppModule {
    private static ADFLogger logger = ADFLogger.createADFLogger(RegionModelAppModuleImpl.class);
    /**
     * This is the default constructor (do not remove).
     */
    public RegionModelAppModuleImpl() {
    }

    /**
     * Container's getter for CountriesView1.
     * @return CountriesView1
     */
    public ViewObjectImpl getCountriesView1() {
        return (ViewObjectImpl)findViewObject("CountriesView1");
    }

    /**
     * Container's getter for LocationsView1.
     * @return LocationsView1
     */
    public ViewObjectImpl getLocationsView1() {
        return (ViewObjectImpl)findViewObject("LocationsView1");
    }

    /**
     * Container's getter for RegionsView1.
     * @return RegionsView1
     */
    public ViewObjectImpl getRegionsView1() {
        return (ViewObjectImpl)findViewObject("RegionsView1");
    }

    /**
     * Container's getter for LocationsView2.
     * @return LocationsView2
     */
    public ViewObjectImpl getLocationsView2() {
        return (ViewObjectImpl)findViewObject("LocationsView2");
    }

    /**
     * Container's getter for CountriesView2.
     * @return CountriesView2
     */
    public ViewObjectImpl getCountriesView2() {
        return (ViewObjectImpl)findViewObject("CountriesView2");
    }

    /**
     * Container's getter for LocCIdFkLink1.
     * @return LocCIdFkLink1
     */
    public ViewLinkImpl getLocCIdFkLink1() {
        return (ViewLinkImpl)findViewLink("LocCIdFkLink1");
    }

    /**
     * Container's getter for CountrRegFkLink1.
     * @return CountrRegFkLink1
     */
    public ViewLinkImpl getCountrRegFkLink1() {
        return (ViewLinkImpl)findViewLink("CountrRegFkLink1");
    }
    
    public String helloRegionModule(String param) {
        logger.info("Param = " + param);
        if (param != null)
            return "Hello " + param;
        return "Can't say hello to nobody";
    }
}
